CREATE DATABASE OLAPAPI;
USE OLAPAPI;

CREATE TABLE D_VIDEOS (
  ID_VIDEO INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  TITULO VARCHAR(1000),
  URL VARCHAR(1000)
);

CREATE TABLE D_ESTADISTICAS (
  ID_ESTADISTICA INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  VISTAS VARCHAR(1000),
  LIKES VARCHAR(1000),
  DISLIKES VARCHAR(1000),
  COMENTARIOS VARCHAR(1000),
  PUBLISHED VARCHAR(1000)
);

CREATE TABLE D_CANAL (
  ID_CANAL INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  NOMBRE VARCHAR(1000)
);

CREATE TABLE H_CANAL (
  ID_CANAL INT PRIMARY KEY NOT NULL IDENTITY(1,1),
  ID_ESTADISTICA INT,
  ID_VIDEO INT,
  VIDEOID VARCHAR(1000),
  FOREIGN KEY (ID_CANAL) REFERENCES D_CANAL(ID_CANAL),
  FOREIGN KEY (ID_VIDEO) REFERENCES D_VIDEOS(ID_VIDEO),
  FOREIGN KEY (ID_ESTADISTICA) REFERENCES D_ESTADISTICAS(ID_ESTADISTICA)
);