CREATE DATABASE OLAPAPI;
USE OLAPAPI;

CREATE TABLE D_VIDEOS (
  ID_VIDEO INT,
  TITULO VARCHAR(1000),
  URL VARCHAR(1000),
  PRIMARY KEY (ID_VIDEO)
);

CREATE TABLE D_ESTADISTICAS (
  ID_ESTADISTICA INT,
  VISTAS VARCHAR(1000),
  LIKES VARCHAR(1000),
  DISLIKES VARCHAR(1000),
  COMENTARIOS VARCHAR(1000),
  PRIMARY KEY (ID_ESTADISTICA)
);

CREATE TABLE D_CANAL (
  ID_CANAL VARCHAR(1000),
  NOMBRE VARCHAR(50),
  PRIMARY KEY (ID_CANAL)
);

CREATE TABLE D_TIEMPO (
  ID_TIEMPO DATE,
  PRIMARY KEY (ID_TIEMPO)
);

CREATE TABLE H_CANAL (
  ID_CANAL VARCHAR(1000),
  ID_ESTADISTICAS INT,
  ID_VIDEOS INT,
  ID_TIEMPO DATE,
  PRIMARY KEY (ID_CANAL),
  FOREIGN KEY (ID_TIEMPO) REFERENCES D_TIEMPO(ID_TIEMPO),
  FOREIGN KEY (ID_CANAL) REFERENCES D_CANAL(ID_CANAL),
  FOREIGN KEY (ID_VIDEOS) REFERENCES D_VIDEOS(ID_VIDEO),
  FOREIGN KEY (ID_ESTADISTICAS) REFERENCES D_ESTADISTICAS(ID_ESTADISTICA)
);



