CREATE DATABASE OLAPEMPLOYEE;
USE OLAPEMPLOYEE;

CREATE TABLE D_VIAJES (
  ID_VIAJE INT PRIMARY KEY NOT NULL,
  DIRECCION VARCHAR(1000),
  ESTADO BIT
);

CREATE TABLE D_SUCURSAL (
  ID_SUCURSAL INT PRIMARY KEY NOT NULL,
  DIRECCION VARCHAR(1000)
);

CREATE TABLE D_TRABAJO (
  ID_TRABAJO INT PRIMARY KEY NOT NULL,
  CARGO VARCHAR(1000)
);

CREATE TABLE D_EMPLEADOS (
  ID_EMPLEADO INT PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(1000),
  RATING VARCHAR(1000)
);

CREATE TABLE D_TIEMPO (
  ID_TIEMPO DATE PRIMARY KEY NOT NULL,
  DIA VARCHAR(1000),
  MES INT,
  AÑO INT,
  TRIMESTRE INT,
  SEMESTRE INT,
  DIADESEMANA VARCHAR(1000)
);

CREATE TABLE H_EMPLEADO (
  ID_H_EMPLEADO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  ID_SUCURSAL INT,
  ID_TRABAJO INT,
  ID_VIAJE INT,
  ID_EMPLEADO INT,
  ID_TIEMPO DATE,
  NOMBREEMPLEADO VARCHAR(1000),

  FOREIGN KEY (ID_TRABAJO) 
  REFERENCES D_TRABAJO(ID_TRABAJO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_TIEMPO) 
  REFERENCES D_TIEMPO(ID_TIEMPO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_EMPLEADO) 
  REFERENCES D_EMPLEADOS(ID_EMPLEADO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_VIAJE) 
  REFERENCES D_VIAJES(ID_VIAJE)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_SUCURSAL) 
  REFERENCES D_SUCURSAL(ID_SUCURSAL)
  ON DELETE CASCADE
);

