CREATE DATABASE OLAPINCOME;
USE OLAPINCOME;

CREATE TABLE D_VIAJES (
  ID_VIAJE INT PRIMARY KEY NOT NULL,
  DIRECCION VARCHAR(1000),
  MONTO INT, 
  ESTADO BIT
);

CREATE TABLE D_SUCURSAL (
  ID_SUCURSAL INT PRIMARY KEY NOT NULL,
  DIRECCION VARCHAR(1000)
);

CREATE TABLE D_MEDIO_DE_TRANSPORTE (
  ID_MEDIO INT PRIMARY KEY NOT NULL,
  CARGA VARCHAR(1000),
  TIPO VARCHAR(1000)
);

CREATE TABLE D_EMPLEADOS (
  ID_EMPLEADO INT PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(1000)
);

CREATE TABLE D_TIEMPO (
  ID_TIEMPO DATE PRIMARY KEY NOT NULL,
  DIA VARCHAR(1000),
  MES INT,
  AÑO INT,
  TRIMESTRE INT,
  SEMESTRE INT,
  DIADESEMANA VARCHAR(1000)
);

CREATE TABLE H_INGRESOS (
  ID_INGRESOS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  ID_SUCURSAL INT,
  ID_EMPLEADOS INT,
  ID_MEDIO INT,
  ID_VIAJES INT,
  ID_TIEMPO INT,
  INGRESO INT,

  FOREIGN KEY (ID_MEDIO) 
  REFERENCES D_MEDIO_DE_TRANSPORTE(ID_MEDIO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_TIEMPO) 
  REFERENCES D_TIEMPO(ID_TIEMPO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_EMPLEADOS) 
  REFERENCES D_EMPLEADOS(ID_EMPLEADO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_VIAJES) 
  REFERENCES D_VIAJES(ID_VIAJE)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_SUCURSAL) 
  REFERENCES D_SUCURSAL(ID_SUCURSAL)
  ON DELETE CASCADE
);


