CREATE DATABASE OLAPINCOME;
USE OLAPINCOME;

CREATE TABLE D_VIAJES (
  ID_VIAJE INT,
  DIRECCION VARCHAR(1000),
  PRIMARY KEY (ID_VIAJE)
);

CREATE TABLE D_SUCURSAL (
  ID_SUCURSAL INT,
  PRIMARY KEY (ID_SUCURSAL)
);

CREATE TABLE D_MEDIO_DE_TRANSPORTE (
  ID_MEDIO INT,
  CARGA VARCHAR(1000),
  TIPO VARCHAR(1000),
  PRIMARY KEY (ID_MEDIO)
);

CREATE TABLE D_EMPLEADOS (
  ID_EMPLEADO INT,
  NOMBRE VARCHAR(50),
  PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE D_TIEMPO (
  ID_TIEMPO DATE,
  DIA VARCHAR(1000),
  MES INT,
  AÑO INT,
  TRIMESTRE INT,
  SEMESTRE INT,
  DIADESEMANA VARCHAR(1000),
  PRIMARY KEY (ID_TIEMPO)
);

CREATE TABLE H_INGRESOS (
  ID_INGRESOS INT,
  ID_SUCURSAL INT,
  ID_EMPLEADOS INT,
  ID_MEDIO INT,
  ID_VIAJES INT,
  ID_TIEMPO INT,
  INGRESO INT,
  PRIMARY KEY (ID_INGRESOS),
  FOREIGN KEY (ID_EMPLEADOS) REFERENCES D_MEDIO_DE_TRANSPORTE(ID_MEDIO),
  FOREIGN KEY (ID_VIAJES) REFERENCES D_TIEMPO(ID_TIEMPO),
  FOREIGN KEY (ID_TIEMPO) REFERENCES D_EMPLEADOS(ID_EMPLEADO),
  FOREIGN KEY (ID_MEDIO) REFERENCES D_VIAJES(ID_VIAJE),
  FOREIGN KEY (ID_SUCURSAL) REFERENCES D_SUCURSAL(ID_SUCURSAL)
);


