CREATE DATABASE OLAPVEHICLE;
USE OLAPVEHICLE;

CREATE TABLE D_VIAJES (
  ID_VIAJE INT,
  DIRECCION VARCHAR(1000),
  PRIMARY KEY (ID_VIAJE)
);

CREATE TABLE D_MARCA (
  ID_MARCA INT,
  NOMBRE VARCHAR(1000),
  PRIMARY KEY (ID_MARCA)
);

CREATE TABLE D_MEDIO_DE_TRANSPORTE (
  ID_TRABAJO INT,
  Cargo VARCHAR(1000),
  PRIMARY KEY (ID_TRABAJO)
);

CREATE TABLE D_VEHÍCULO (
  ID_VEHICULO INT,
  NOMBRE VARCHAR(1000),
  PRIMARY KEY (ID_VEHICULO)
);

CREATE TABLE D_TIEMPO (
  ID_TIEMPO DATE,
  FECHA DATE,
  PRIMARY KEY (ID_TIEMPO)
);

CREATE TABLE H_VEHICULO (
  ID_H_VEHÍCULO INT,
  ID_MARCA INT,
  ID_MEDIO INT,
  ID_VIAJES INT,
  ID_TIEMPO DATE,
  ID_VEHÍCULO INT,
  NOMBRECLIENTE VARCHAR(1000),
  PRIMARY KEY (ID_H_VEHÍCULO),
  FOREIGN KEY (ID_MEDIO) REFERENCES D_MEDIO_DE_TRANSPORTE(ID_TRABAJO),
  FOREIGN KEY (ID_TIEMPO) REFERENCES D_TIEMPO(ID_TIEMPO),
  FOREIGN KEY (ID_VEHÍCULO) REFERENCES D_VEHÍCULO(ID_VEHICULO),
  FOREIGN KEY (ID_VIAJES) REFERENCES D_VIAJES(ID_VIAJE),
  FOREIGN KEY (ID_MARCA) REFERENCES D_MARCA(ID_MARCA)
);


