CREATE DATABASE OLAPVEHICLE;
USE OLAPVEHICLE;

CREATE TABLE D_VIAJES (
  ID_VIAJE INT PRIMARY KEY NOT NULL,
  DIRECCION VARCHAR(1000),
  MONTO INT, 
  ESTADO BIT
);

CREATE TABLE D_MARCA (
  ID_MARCA INT PRIMARY KEY NOT NULL,
  NOMBRE VARCHAR(1000)
);

CREATE TABLE D_MEDIO_DE_TRANSPORTE (
  ID_MEDIO INT PRIMARY KEY NOT NULL,
  TIPOMEDIO VARCHAR(1000)
);

CREATE TABLE D_VEHICULO (
  ID_VEHICULO INT NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR(1000)
);

CREATE TABLE D_TIEMPO (
  ID_TIEMPO DATE PRIMARY KEY NOT NULL,
  DIA VARCHAR(1000),
  MES INT,
  AÑO INT,
  TRIMESTRE INT,
  SEMESTRE INT,
  DIADESEMANA VARCHAR(1000)
);

CREATE TABLE H_VEHICULO (
  ID_H_VEHICULO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  ID_MARCA INT,
  ID_MEDIO INT,
  ID_VIAJE INT,
  ID_TIEMPO DATE,
  ID_VEHICULO INT,
  NOMBRECLIENTE VARCHAR(1000),

  FOREIGN KEY (ID_MEDIO) 
  REFERENCES D_MEDIO_DE_TRANSPORTE(ID_MEDIO) 
  ON DELETE CASCADE,

  FOREIGN KEY (ID_TIEMPO) 
  REFERENCES D_TIEMPO(ID_TIEMPO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_VEHICULO) 
  REFERENCES D_VEHICULO(ID_VEHICULO)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_VIAJE) 
  REFERENCES D_VIAJES(ID_VIAJE)
  ON DELETE CASCADE,

  FOREIGN KEY (ID_MARCA) 
  REFERENCES D_MARCA(ID_MARCA)
  ON DELETE CASCADE
);


